import { AdminSessionProvider } from "../../../contexts/auth/SessionContext";
import { SidebarProvider } from "../../../contexts/SidebarContext";
import LayoutWrapper from "./AdminLayoutWrapper";

export const metadata = {
  title: "BTM",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <AdminSessionProvider>
      <SidebarProvider>
        <LayoutWrapper>{children}</LayoutWrapper>
      </SidebarProvider>
    </AdminSessionProvider>
  );
}
