import {
  Bell,
  BookCheck,
  CalendarCheck2,
  ChartBarBig,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheckBig,
  CirclePlus,
  CircleUser,
  ClipboardPlus,
  Clock,
  CreditCard,
  File,
  Headset,
  HeartHandshake,
  Info,
  KeyRound,
  LayoutDashboard,
  ListTodo,
  LogIn,
  Mail,
  MessageSquareMore,
  MessageSquareText,
  Pencil,
  Search,
  Settings,
  ShieldAlert,
  ShoppingCart,
  Smartphone,
  Table,
  TriangleAlert,
  Users,
  X,
  House
} from "lucide-react";

export const Icons = {
  user: Users,
  alert: ShieldAlert,
  bell: Bell,
  cart: ShoppingCart,
  message: MessageSquareText,
  dashboard: LayoutDashboard,
  carrowdown: ChevronDown,
  chartBar: ChartBarBig,
  chartLine: ChartLine,
  report: ClipboardPlus,
  settings: Settings,
  userCircle: CircleUser,
  helpCircle: HeartHandshake,
  feedback: MessageSquareMore,
  fileText: File,
  headset: Headset,
  creditCard: CreditCard,
  edit: Pencil,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  search: Search,
  key: KeyRound,
  login: LogIn,
  table: Table,
  plus: CirclePlus,
  check: Check,
  book: BookCheck,
  mail: Mail,
  phone: Smartphone,
  checkCircle: CircleCheckBig,
  xCircle: CircleAlert,
  alertTriangle: TriangleAlert,
  info: Info,
  x: X,
  list:ListTodo,
  clock:Clock,
  calender:CalendarCheck2,
  home:House
};